{% set name = "snntoolbox" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snntoolbox-{{ version }}.tar.gz
  sha256: e0a327fc3641adaef2910deca16df4f717f8dced9605fcfc2703ef930f681a52
  patches:
    - fix-missing-requirements.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - tensorflow

test:
  imports:
    - snntoolbox
  # commands:
  #   - pip check
  requires:
  #   - pip
    - python {{ python_min }}

about:
  home: https://github.com/NeuromorphicProcessorProject/snn_toolbox
  summary: Spiking neural network conversion toolbox
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
